---
title: "Decision Tree/Random Forest"
output: html_notebook
---



```{r}
library(ISLR)
library(ggplot2)

head(College)

df <- College
```


```{r}
ggplot(df, aes(Room.Board, Grad.Rate)) + geom_point(aes(color=Private))
ggplot(df, aes(F.Undergrad)) + geom_histogram(aes(fill=Private), color='black', bins=50, alpha=0.5) + theme_bw()
ggplot(df, aes(Grad.Rate))+geom_histogram(aes(fill=Private), color='black', bins=50, alpha=0.6) + theme_bw()
```


update outlier with rate over 100 to 100
```{r}
subset(df, Grad.Rate >100)
df['Cazenovia College','Grad.Rate'] <- 100
```


```{r}
library(caTools)
set.seed(101)

sample <- sample.split(df$Private, SplitRatio= 0.70)
train <- subset(df, sample == T)
test <- subset(df, sample == F)
```

```{r}
library(rpart)
tree <-rpart(Private ~ ., method='class', data=train)
tree.preds <- predict(tree, test)
head(tree.preds)
```

```{r}
tree.preds <- as.data.frame(tree.preds)

joiner <- function(x){
  if (x>=0.5){
    return('Yes')
  }else{
    return('No')
  }
}
```

```{r}
tree.preds$Private <- sapply(tree.preds$Yes, joiner)
print(head(tree.preds))
```

```{r}
table(tree.preds$Private, test$Private)
```

```{r}
prp(tree)
```

```{r}
library(randomForest)
rf.model <- randomForest(Private ~ ., data=train, importance = TRUE)
rf.model$confusion
```

```{r}
rf.model$importance
```

```{r}
rf.preds <- predict(rf.model, test)
table(rf.preds, test$Private)
```

